author= "AbdelRahim Elmadany, Moataz Nagoudi, and Muhammad Abdul-Mageed"
copyright= "Copyright 2023, University of British Columbia (UBC), Deep learning and Natural Langauge Processing Lab"
license= "GPL"
version= "0.0.1"
email= "a.elmadany@ubc.ca"
status= "Production"
description="OCTOPUS: A Multitask Model and Toolkit for Arabic Natural Language Generation"